name: Run tests

on: [push, pull_request]

jobs:
    format:
        name: Run tests
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                path: /home/runner/work/headers.nvim/headers.nvim

            - name: Install
              run: |
                curl -LO https://github.com/neovim/neovim/releases/latest/download/nvim-linux64.tar.gz
                sudo rm -rf /opt/nvim
                sudo tar -C /opt -xzf nvim-linux64.tar.gz

                echo 'export PATH="$PATH:/opt/nvim-linux64/bin"' >> /home/runner/.bashrc

            - name: Setup
              timeout-minutes: 2
              run: |
                set +e
                mkdir -p /home/runner/.config/nvim
                cp /home/runner/work/headers.nvim/headers.nvim/.github/workflows/init.lua /home/runner/.config/nvim

                nvim --headless +qa

            - name: Tests
              timeout-minutes: 2
              run: |
                set +e

                log=$(make)

                if [[ $? -ne 0 ]]; then
                  echo "::error title=Tests failed::$log"
                  exit 1
                fi
